# Generated by Django 4.2.10 on 2024-02-27 14:07

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField(default=0)),
                ('appsSection', models.ManyToManyField(blank=True, to='products.application')),
                ('codeProgsSection', models.ManyToManyField(blank=True, to='products.programmecode')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120, null=True)),
                ('username', models.CharField(max_length=120, null=True, unique=True)),
                ('email', models.CharField(max_length=120, null=True, unique=True)),
                ('cellphone', models.BigIntegerField(blank=True, null=True)),
                ('quote', models.CharField(blank=True, max_length=120, null=True)),
                ('registrationDate', models.DateField(blank=True, null=True)),
                ('listOfAllPurchases', models.TextField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('cartItems', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.shoppingcart')),
                ('purchasedApps', models.ManyToManyField(blank=True, related_name='accessedApps', to='products.application')),
                ('purchasedProgCodes', models.ManyToManyField(blank=True, related_name='accessedProgCodes', to='products.programmecode')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', members.models.MemberManager()),
            ],
        ),
    ]
