# Generated by Django 4.2.10 on 2024-02-27 14:07

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(null=True)),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[500, None], upload_to='images/')),
                ('demo', models.URLField(blank=True, null=True)),
                ('sourceFile', models.FileField(null=True, upload_to='appFiles/')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(null=True)),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[500, None], upload_to='images/')),
                ('demo', models.URLField(blank=True, null=True)),
                ('sourceFile', models.FileField(null=True, upload_to='codeFiles/')),
            ],
        ),
    ]
